ldap-explorer:
  ldap:
    init-ctx-factory: ${LDAP_INIT_CTX_FACTORY:com.sun.jndi.ldap.LdapCtxFactory}

quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      driver: org.postgresql.Driver
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}?currentSchema=${DB_SCHEMA:public}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  flyway:
    default-schema: ${DB_SCHEMA:public}
    migrate-at-start: true
    locations: db/0_tables,db/1_data
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    baseline-version: ${FLYWAY_BASELINE_VERSION:0}

  log:
    console:
      color: true
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}:%L] %s%e%n"

  naming:
    enable-jndi: true

  quinoa:
    build-dir: dist/ldap-explorer/browser
    enable-spa-routing: true
    force-install: true
    package-manager-command:
      install: install --force

  rest:
    path: /api/v1

  thread-pool:
    core-threads: 5
    queue-size: 20
    max-threads: 20

  tls:
    trust-all: true

  transaction-manager:
    default-transaction-timeout: ${DB_TIMEOUT:1200s}
